version: '3'
services:
  db:
    image: postgres:11-alpine
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        - FOLDERS_TO_REMOVE=
        - ADDITIONAL_PACKAGES=nodejs-current
        - EXECJS_RUNTIME=Node
        - BUNDLE_WITHOUT=production
        - RAILS_ENV=test
    environment:
      - RAILS_ENV=test
    ports:
      - 3000
    depends_on:
      - db

volumes:
  db-data:
