version: '3.7'

services:
  web:
    image: nginx
    volumes:
      - ./vhost.template:/etc/nginx/conf.d/vhost.template
      - static-content:/app/public
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      - NGINX_HOSTS=_
    command: >
      /bin/bash -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\"
      < /etc/nginx/conf.d/vhost.template
      > /etc/nginx/conf.d/default.conf
      && exec nginx -g 'daemon off;'"

  db:
    image: postgres:11-alpine
    ports:
      - 5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - /my-volumes/docker-kickstart/postgresql:/var/lib/postgresql/data

  app:
    image: 135594858514.dkr.ecr.eu-central-1.amazonaws.com/simplificator/kickstart:master
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - RAILS_MAX_THREADS=5
      - VIRTUAL_HOST=localhost
    depends_on:
      - db
    volumes:
      - static-content:/app/public
    ports:
      - 3000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 5m
      start_period: 1m

volumes:
  static-content:
