
- hosts: all

  roles:
    - app_user

  tasks:
  - name: "Add authorized keys for root"
    copy:
      content: "{{ authorized_keys['root'] }}"
      dest: "~root/.ssh/authorized_keys"
      owner: "root"
      group: "root"
      mode: 0600
    when: authorized_keys['root'] is defined

  - name: "Copy deployment files"
    copy:
      src: "{{ item }}"
      dest: "/home/{{ app_user }}/{{ item }}"
      owner: "{{ app_user }}"
      group: "{{ app_user }}"
      mode: +x
    loop:
      - docker-compose.yml
      - deploy.sh

  - name: Run deploy.sh
    shell: ./deploy.sh
    args:
      chdir: "/home/{{ app_user }}/"
      executable: /bin/bash
    environment:
      AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
      AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
